#!/bin/bash
docker buildx create --name=buildx-multi-arch --driver=docker-container --driver-opt=network=host
docker buildx build --push --builder=buildx-multi-arch --platform=linux/amd64,linux/arm64 --build-arg TAG=$DOCKER_TAG --tag=$IMAGE_NAME .